declare type Alignment = 'start start'
    | 'start space-between'
    | 'start sb'
    | 'start'
    | 'start center'
    | 'start ctr'
    | 'start space-around'
    | 'start sa'
    | 'start stretch'
    | 'start end'
    | 'space-between start'
    | 'sb start'
    | 'space-between space-between'
    | 'sb'
    | 'space-between center'
    | 'sb ctr'
    | 'space-between space-around'
    | 'sb sa'
    | 'space-between stretch'
    | 'sb stretch'
    | 'space-between end'
    | 'sb end'
    | 'center start'
    | 'ctr start'
    | 'center space-between'
    | 'ctr sb'
    | 'center center'
    | 'ctr'
    | 'center space-around'
    | 'ctr sa'
    | 'center stretch'
    | 'ctr stretch'
    | 'center end'
    | 'ctr end'
    | 'stretch start'
    | 'stretch space-between'
    | 'stretch sb'
    | 'stretch center'
    | 'stretch ctr'
    | 'stretch space-around'
    | 'stretch sa'
    | 'stretch stretch'
    | 'stretch'
    | 'stretch end'
    | 'space-around start'
    | 'sa start'
    | 'space-around space-between'
    | 'sa sb'
    | 'space-around center'
    | 'sa ctr'
    | 'space-around space-around'
    | 'sa'
    | 'space-around stretch'
    | 'sa stretch'
    | 'space-around end'
    | 'sa end'
    | 'end start'
    | 'end space-between'
    | 'end sb'
    | 'end center'
    | 'end ctr'
    | 'end space-around'
    | 'end sa'
    | 'end stretch'
    | 'end end'
    | 'end';

declare type Columns = '0'
    | '1' | '2' | '3'
    | '4' | '5' | '6'
    | '7' | '8' | '9'
    | '10' | '11' | '12';
